// 元素数据 - Periodic Table Elements Data
const elementsData = {
    1: {
        symbol: 'H',
        name: '氢',
        englishName: 'Hydrogen',
        atomicNumber: 1,
        atomicMass: 1.008,
        group: 1,
        period: 1,
        category: 'nonmetal',
        electronConfiguration: '1s¹',
        electronegativity: 2.20,
        atomicRadius: 25,
        ionizationEnergy: 1312,
        meltingPoint: -259.16,
        boilingPoint: -252.87,
        density: 0.00008988,
        state: 'gas',
        oxidationStates: [-1, 1],
        bondingType: 'covalent',
        crystalStructure: 'hexagonal',
        thermalConductivity: 0.1805,
        electricalResistivity: null,
        magneticOrdering: 'diamagnetic',
        speedOfSound: 1310,
        modulus: { bulk: null, shear: null, young: null },
        hardness: { mohs: null, vickers: null, brinell: null },
        abundance: { earth: 0.14, universe: 75 }
    },
    2: {
        symbol: 'He',
        name: '氦',
        englishName: 'Helium',
        atomicNumber: 2,
        atomicMass: 4.0026,
        group: 18,
        period: 1,
        category: 'noble-gas',
        electronConfiguration: '1s²',
        electronegativity: null,
        atomicRadius: 31,
        ionizationEnergy: 2372,
        meltingPoint: -272.20,
        boilingPoint: -268.93,
        density: 0.0001785,
        state: 'gas',
        oxidationStates: [0],
        bondingType: 'van der waals',
        crystalStructure: 'hexagonal close-packed',
        thermalConductivity: 0.1513,
        electricalResistivity: null,
        magneticOrdering: 'diamagnetic',
        speedOfSound: 972,
        modulus: { bulk: null, shear: null, young: null },
        hardness: { mohs: null, vickers: null, brinell: null },
        abundance: { earth: 0.000008, universe: 23 }
    },
    3: {
        symbol: 'Li',
        name: '锂',
        englishName: 'Lithium',
        atomicNumber: 3,
        atomicMass: 6.94,
        group: 1,
        period: 2,
        category: 'alkali-metal',
        electronConfiguration: '[He] 2s¹',
        electronegativity: 0.98,
        atomicRadius: 128,
        ionizationEnergy: 520,
        meltingPoint: 180.50,
        boilingPoint: 1342,
        density: 0.534,
        state: 'solid',
        oxidationStates: [1],
        bondingType: 'metallic',
        crystalStructure: 'body-centered cubic',
        thermalConductivity: 84.8,
        electricalResistivity: 92.8,
        magneticOrdering: 'paramagnetic',
        speedOfSound: 6000,
        modulus: { bulk: 11, shear: 4.2, young: 4.9 },
        hardness: { mohs: 0.6, vickers: null, brinell: null },
        abundance: { earth: 0.002, universe: 0.0000006 }
    },
    4: {
        symbol: 'Be',
        name: '铍',
        englishName: 'Beryllium',
        atomicNumber: 4,
        atomicMass: 9.0122,
        group: 2,
        period: 2,
        category: 'alkaline-earth',
        electronConfiguration: '[He] 2s²',
        electronegativity: 1.57,
        atomicRadius: 96,
        ionizationEnergy: 899,
        meltingPoint: 1287,
        boilingPoint: 2471,
        density: 1.85,
        state: 'solid',
        oxidationStates: [2],
        bondingType: 'metallic',
        crystalStructure: 'hexagonal close-packed',
        thermalConductivity: 190,
        electricalResistivity: 36,
        magneticOrdering: 'diamagnetic',
        speedOfSound: 13000,
        modulus: { bulk: 130, shear: 132, young: 287 },
        hardness: { mohs: 5.5, vickers: 1670, brinell: 600 },
        abundance: { earth: 0.00019, universe: 0.000001 }
    },
    5: {
        symbol: 'B',
        name: '硼',
        englishName: 'Boron',
        atomicNumber: 5,
        atomicMass: 10.81,
        group: 13,
        period: 2,
        category: 'metalloid',
        electronConfiguration: '[He] 2s² 2p¹',
        electronegativity: 2.04,
        atomicRadius: 84,
        ionizationEnergy: 801,
        meltingPoint: 2077,
        boilingPoint: 4000,
        density: 2.37,
        state: 'solid',
        oxidationStates: [3],
        bondingType: 'covalent network',
        crystalStructure: 'rhombohedral',
        thermalConductivity: 27.4,
        electricalResistivity: 10000000000000,
        magneticOrdering: 'diamagnetic',
        speedOfSound: 16200,
        modulus: { bulk: 320, shear: null, young: null },
        hardness: { mohs: 9.3, vickers: 49000, brinell: null },
        abundance: { earth: 0.001, universe: 0.000001 }
    },
    6: {
        symbol: 'C',
        name: '碳',
        englishName: 'Carbon',
        atomicNumber: 6,
        atomicMass: 12.011,
        group: 14,
        period: 2,
        category: 'nonmetal',
        electronConfiguration: '[He] 2s² 2p²',
        electronegativity: 2.55,
        atomicRadius: 76,
        ionizationEnergy: 1086,
        meltingPoint: 3550,
        boilingPoint: 4027,
        density: 2.267,
        state: 'solid',
        oxidationStates: [-4, -3, -2, -1, 1, 2, 3, 4],
        bondingType: 'covalent network',
        crystalStructure: 'hexagonal',
        thermalConductivity: 129,
        electricalResistivity: 0.00001,
        magneticOrdering: 'diamagnetic',
        speedOfSound: 18350,
        modulus: { bulk: 33, shear: null, young: null },
        hardness: { mohs: 10, vickers: null, brinell: null },
        abundance: { earth: 0.02, universe: 0.46 }
    },
    7: {
        symbol: 'N',
        name: '氮',
        englishName: 'Nitrogen',
        atomicNumber: 7,
        atomicMass: 14.007,
        group: 15,
        period: 2,
        category: 'nonmetal',
        electronConfiguration: '[He] 2s² 2p³',
        electronegativity: 3.04,
        atomicRadius: 71,
        ionizationEnergy: 1402,
        meltingPoint: -210.00,
        boilingPoint: -195.79,
        density: 0.0012506,
        state: 'gas',
        oxidationStates: [-3, -2, -1, 1, 2, 3, 4, 5],
        bondingType: 'covalent',
        crystalStructure: 'hexagonal',
        thermalConductivity: 0.02583,
        electricalResistivity: null,
        magneticOrdering: 'diamagnetic',
        speedOfSound: 334,
        modulus: { bulk: null, shear: null, young: null },
        hardness: { mohs: null, vickers: null, brinell: null },
        abundance: { earth: 0.0025, universe: 0.096 }
    },
    8: {
        symbol: 'O',
        name: '氧',
        englishName: 'Oxygen',
        atomicNumber: 8,
        atomicMass: 15.999,
        group: 16,
        period: 2,
        category: 'nonmetal',
        electronConfiguration: '[He] 2s² 2p⁴',
        electronegativity: 3.44,
        atomicRadius: 66,
        ionizationEnergy: 1314,
        meltingPoint: -218.79,
        boilingPoint: -182.96,
        density: 0.001429,
        state: 'gas',
        oxidationStates: [-2, -1, 1, 2],
        bondingType: 'covalent',
        crystalStructure: 'cubic',
        thermalConductivity: 0.02658,
        electricalResistivity: null,
        magneticOrdering: 'paramagnetic',
        speedOfSound: 316,
        modulus: { bulk: null, shear: null, young: null },
        hardness: { mohs: null, vickers: null, brinell: null },
        abundance: { earth: 46.1, universe: 1.04 }
    }
    // 更多元素数据将在这里添加...
};

// 元素分类
const elementCategories = {
    'alkali-metal': { name: '碱金属', color: '#ffcdd2' },
    'alkaline-earth': { name: '碱土金属', color: '#ffe0b2' },
    'transition-metal': { name: '过渡金属', color: '#c8e6c9' },
    'post-transition': { name: '后过渡金属', color: '#bbdefb' },
    'metalloid': { name: '类金属', color: '#e1bee7' },
    'nonmetal': { name: '非金属', color: '#ffecb3' },
    'halogen': { name: '卤素', color: '#b2dfdb' },
    'noble-gas': { name: '稀有气体', color: '#f8bbd9' },
    'lanthanide': { name: '镧系', color: '#dcedc8' },
    'actinide': { name: '锕系', color: '#fff59d' }
};

// 扩展元素数据到118个元素（简化版本）
function generateFullElementsData() {
    const basicElements = [
        // 第3周期
        { symbol: 'Na', name: '钠', englishName: 'Sodium', atomicNumber: 11, atomicMass: 22.990, group: 1, period: 3, category: 'alkali-metal' },
        { symbol: 'Mg', name: '镁', englishName: 'Magnesium', atomicNumber: 12, atomicMass: 24.305, group: 2, period: 3, category: 'alkaline-earth' },
        { symbol: 'Al', name: '铝', englishName: 'Aluminum', atomicNumber: 13, atomicMass: 26.982, group: 13, period: 3, category: 'post-transition' },
        { symbol: 'Si', name: '硅', englishName: 'Silicon', atomicNumber: 14, atomicMass: 28.085, group: 14, period: 3, category: 'metalloid' },
        { symbol: 'P', name: '磷', englishName: 'Phosphorus', atomicNumber: 15, atomicMass: 30.974, group: 15, period: 3, category: 'nonmetal' },
        { symbol: 'S', name: '硫', englishName: 'Sulfur', atomicNumber: 16, atomicMass: 32.06, group: 16, period: 3, category: 'nonmetal' },
        { symbol: 'Cl', name: '氯', englishName: 'Chlorine', atomicNumber: 17, atomicMass: 35.45, group: 17, period: 3, category: 'halogen' },
        { symbol: 'Ar', name: '氩', englishName: 'Argon', atomicNumber: 18, atomicMass: 39.948, group: 18, period: 3, category: 'noble-gas' },
        
        // 第4周期
        { symbol: 'K', name: '钾', englishName: 'Potassium', atomicNumber: 19, atomicMass: 39.098, group: 1, period: 4, category: 'alkali-metal' },
        { symbol: 'Ca', name: '钙', englishName: 'Calcium', atomicNumber: 20, atomicMass: 40.078, group: 2, period: 4, category: 'alkaline-earth' },
        { symbol: 'Sc', name: '钪', englishName: 'Scandium', atomicNumber: 21, atomicMass: 44.956, group: 3, period: 4, category: 'transition-metal' },
        { symbol: 'Ti', name: '钛', englishName: 'Titanium', atomicNumber: 22, atomicMass: 47.867, group: 4, period: 4, category: 'transition-metal' },
        { symbol: 'V', name: '钒', englishName: 'Vanadium', atomicNumber: 23, atomicMass: 50.942, group: 5, period: 4, category: 'transition-metal' },
        { symbol: 'Cr', name: '铬', englishName: 'Chromium', atomicNumber: 24, atomicMass: 51.996, group: 6, period: 4, category: 'transition-metal' },
        { symbol: 'Mn', name: '锰', englishName: 'Manganese', atomicNumber: 25, atomicMass: 54.938, group: 7, period: 4, category: 'transition-metal' },
        { symbol: 'Fe', name: '铁', englishName: 'Iron', atomicNumber: 26, atomicMass: 55.845, group: 8, period: 4, category: 'transition-metal' },
        { symbol: 'Co', name: '钴', englishName: 'Cobalt', atomicNumber: 27, atomicMass: 58.933, group: 9, period: 4, category: 'transition-metal' },
        { symbol: 'Ni', name: '镍', englishName: 'Nickel', atomicNumber: 28, atomicMass: 58.693, group: 10, period: 4, category: 'transition-metal' },
        { symbol: 'Cu', name: '铜', englishName: 'Copper', atomicNumber: 29, atomicMass: 63.546, group: 11, period: 4, category: 'transition-metal' },
        { symbol: 'Zn', name: '锌', englishName: 'Zinc', atomicNumber: 30, atomicMass: 65.38, group: 12, period: 4, category: 'transition-metal' },
        { symbol: 'Ga', name: '镓', englishName: 'Gallium', atomicNumber: 31, atomicMass: 69.723, group: 13, period: 4, category: 'post-transition' },
        { symbol: 'Ge', name: '锗', englishName: 'Germanium', atomicNumber: 32, atomicMass: 72.630, group: 14, period: 4, category: 'metalloid' },
        { symbol: 'As', name: '砷', englishName: 'Arsenic', atomicNumber: 33, atomicMass: 74.922, group: 15, period: 4, category: 'metalloid' },
        { symbol: 'Se', name: '硒', englishName: 'Selenium', atomicNumber: 34, atomicMass: 78.971, group: 16, period: 4, category: 'nonmetal' },
        { symbol: 'Br', name: '溴', englishName: 'Bromine', atomicNumber: 35, atomicMass: 79.904, group: 17, period: 4, category: 'halogen' },
        { symbol: 'Kr', name: '氪', englishName: 'Krypton', atomicNumber: 36, atomicMass: 83.798, group: 18, period: 4, category: 'noble-gas' }
    ];

    // 将基础元素数据合并到详细数据中
    basicElements.forEach(element => {
        if (!elementsData[element.atomicNumber]) {
            elementsData[element.atomicNumber] = {
                ...element,
                electronConfiguration: 'Unknown',
                electronegativity: null,
                atomicRadius: null,
                ionizationEnergy: null,
                meltingPoint: null,
                boilingPoint: null,
                density: null,
                state: 'unknown',
                oxidationStates: [],
                bondingType: 'unknown',
                crystalStructure: 'unknown',
                thermalConductivity: null,
                electricalResistivity: null,
                magneticOrdering: 'unknown',
                speedOfSound: null,
                modulus: { bulk: null, shear: null, young: null },
                hardness: { mohs: null, vickers: null, brinell: null },
                abundance: { earth: null, universe: null }
            };
        }
    });

    // 为演示目的，添加一些第5-7周期的重要元素
    const importantElements = [
        // 第5周期
        { symbol: 'Rb', name: '铷', englishName: 'Rubidium', atomicNumber: 37, group: 1, period: 5, category: 'alkali-metal' },
        { symbol: 'Sr', name: '锶', englishName: 'Strontium', atomicNumber: 38, group: 2, period: 5, category: 'alkaline-earth' },
        { symbol: 'Y', name: '钇', englishName: 'Yttrium', atomicNumber: 39, group: 3, period: 5, category: 'transition-metal' },
        { symbol: 'Zr', name: '锆', englishName: 'Zirconium', atomicNumber: 40, group: 4, period: 5, category: 'transition-metal' },
        { symbol: 'Nb', name: '铌', englishName: 'Niobium', atomicNumber: 41, group: 5, period: 5, category: 'transition-metal' },
        { symbol: 'Mo', name: '钼', englishName: 'Molybdenum', atomicNumber: 42, group: 6, period: 5, category: 'transition-metal' },
        { symbol: 'Tc', name: '锝', englishName: 'Technetium', atomicNumber: 43, group: 7, period: 5, category: 'transition-metal' },
        { symbol: 'Ru', name: '钌', englishName: 'Ruthenium', atomicNumber: 44, group: 8, period: 5, category: 'transition-metal' },
        { symbol: 'Rh', name: '铑', englishName: 'Rhodium', atomicNumber: 45, group: 9, period: 5, category: 'transition-metal' },
        { symbol: 'Pd', name: '钯', englishName: 'Palladium', atomicNumber: 46, group: 10, period: 5, category: 'transition-metal' },
        { symbol: 'Ag', name: '银', englishName: 'Silver', atomicNumber: 47, group: 11, period: 5, category: 'transition-metal' },
        { symbol: 'Cd', name: '镉', englishName: 'Cadmium', atomicNumber: 48, group: 12, period: 5, category: 'transition-metal' },
        { symbol: 'In', name: '铟', englishName: 'Indium', atomicNumber: 49, group: 13, period: 5, category: 'post-transition' },
        { symbol: 'Sn', name: '锡', englishName: 'Tin', atomicNumber: 50, group: 14, period: 5, category: 'post-transition' },
        { symbol: 'Sb', name: '锑', englishName: 'Antimony', atomicNumber: 51, group: 15, period: 5, category: 'metalloid' },
        { symbol: 'Te', name: '碲', englishName: 'Tellurium', atomicNumber: 52, group: 16, period: 5, category: 'metalloid' },
        { symbol: 'I', name: '碘', englishName: 'Iodine', atomicNumber: 53, group: 17, period: 5, category: 'halogen' },
        { symbol: 'Xe', name: '氙', englishName: 'Xenon', atomicNumber: 54, group: 18, period: 5, category: 'noble-gas' },

        // 第6周期
        { symbol: 'Cs', name: '铯', englishName: 'Cesium', atomicNumber: 55, group: 1, period: 6, category: 'alkali-metal' },
        { symbol: 'Ba', name: '钡', englishName: 'Barium', atomicNumber: 56, group: 2, period: 6, category: 'alkaline-earth' },
        { symbol: 'La', name: '镧', englishName: 'Lanthanum', atomicNumber: 57, group: 3, period: 6, category: 'lanthanide' },
        { symbol: 'Hf', name: '铪', englishName: 'Hafnium', atomicNumber: 72, group: 4, period: 6, category: 'transition-metal' },
        { symbol: 'Ta', name: '钽', englishName: 'Tantalum', atomicNumber: 73, group: 5, period: 6, category: 'transition-metal' },
        { symbol: 'W', name: '钨', englishName: 'Tungsten', atomicNumber: 74, group: 6, period: 6, category: 'transition-metal' },
        { symbol: 'Re', name: '铼', englishName: 'Rhenium', atomicNumber: 75, group: 7, period: 6, category: 'transition-metal' },
        { symbol: 'Os', name: '锇', englishName: 'Osmium', atomicNumber: 76, group: 8, period: 6, category: 'transition-metal' },
        { symbol: 'Ir', name: '铱', englishName: 'Iridium', atomicNumber: 77, group: 9, period: 6, category: 'transition-metal' },
        { symbol: 'Pt', name: '铂', englishName: 'Platinum', atomicNumber: 78, group: 10, period: 6, category: 'transition-metal' },
        { symbol: 'Au', name: '金', englishName: 'Gold', atomicNumber: 79, group: 11, period: 6, category: 'transition-metal' },
        { symbol: 'Hg', name: '汞', englishName: 'Mercury', atomicNumber: 80, group: 12, period: 6, category: 'transition-metal' },
        { symbol: 'Tl', name: '铊', englishName: 'Thallium', atomicNumber: 81, group: 13, period: 6, category: 'post-transition' },
        { symbol: 'Pb', name: '铅', englishName: 'Lead', atomicNumber: 82, group: 14, period: 6, category: 'post-transition' },
        { symbol: 'Bi', name: '铋', englishName: 'Bismuth', atomicNumber: 83, group: 15, period: 6, category: 'post-transition' },
        { symbol: 'Po', name: '钋', englishName: 'Polonium', atomicNumber: 84, group: 16, period: 6, category: 'post-transition' },
        { symbol: 'At', name: '砹', englishName: 'Astatine', atomicNumber: 85, group: 17, period: 6, category: 'halogen' },
        { symbol: 'Rn', name: '氡', englishName: 'Radon', atomicNumber: 86, group: 18, period: 6, category: 'noble-gas' },

        // 第7周期
        { symbol: 'Fr', name: '钫', englishName: 'Francium', atomicNumber: 87, group: 1, period: 7, category: 'alkali-metal' },
        { symbol: 'Ra', name: '镭', englishName: 'Radium', atomicNumber: 88, group: 2, period: 7, category: 'alkaline-earth' },
        { symbol: 'Ac', name: '锕', englishName: 'Actinium', atomicNumber: 89, group: 3, period: 7, category: 'actinide' },
        { symbol: 'Rf', name: '𬬻', englishName: 'Rutherfordium', atomicNumber: 104, group: 4, period: 7, category: 'transition-metal' },
        { symbol: 'Db', name: '𬭊', englishName: 'Dubnium', atomicNumber: 105, group: 5, period: 7, category: 'transition-metal' },
        { symbol: 'Sg', name: '𬭳', englishName: 'Seaborgium', atomicNumber: 106, group: 6, period: 7, category: 'transition-metal' },
        { symbol: 'Bh', name: '𬭛', englishName: 'Bohrium', atomicNumber: 107, group: 7, period: 7, category: 'transition-metal' },
        { symbol: 'Hs', name: '𬭶', englishName: 'Hassium', atomicNumber: 108, group: 8, period: 7, category: 'transition-metal' },
        { symbol: 'Mt', name: '鿏', englishName: 'Meitnerium', atomicNumber: 109, group: 9, period: 7, category: 'transition-metal' },
        { symbol: 'Ds', name: '𫟼', englishName: 'Darmstadtium', atomicNumber: 110, group: 10, period: 7, category: 'transition-metal' },
        { symbol: 'Rg', name: '𬬮', englishName: 'Roentgenium', atomicNumber: 111, group: 11, period: 7, category: 'transition-metal' },
        { symbol: 'Cn', name: '鿔', englishName: 'Copernicium', atomicNumber: 112, group: 12, period: 7, category: 'transition-metal' },
        { symbol: 'Nh', name: '鿭', englishName: 'Nihonium', atomicNumber: 113, group: 13, period: 7, category: 'post-transition' },
        { symbol: 'Fl', name: '𫓧', englishName: 'Flerovium', atomicNumber: 114, group: 14, period: 7, category: 'post-transition' },
        { symbol: 'Mc', name: '镆', englishName: 'Moscovium', atomicNumber: 115, group: 15, period: 7, category: 'post-transition' },
        { symbol: 'Lv', name: '𫟷', englishName: 'Livermorium', atomicNumber: 116, group: 16, period: 7, category: 'post-transition' },
        { symbol: 'Ts', name: '鿬', englishName: 'Tennessine', atomicNumber: 117, group: 17, period: 7, category: 'halogen' },
        { symbol: 'Og', name: '鿫', englishName: 'Oganesson', atomicNumber: 118, group: 18, period: 7, category: 'noble-gas' }
    ];

    // 镧系元素
    const lanthanides = [
        { symbol: 'Ce', name: '铈', englishName: 'Cerium', atomicNumber: 58, group: 'lanthanide', period: 6, category: 'lanthanide' },
        { symbol: 'Pr', name: '镨', englishName: 'Praseodymium', atomicNumber: 59, group: 'lanthanide', period: 6, category: 'lanthanide' },
        { symbol: 'Nd', name: '钕', englishName: 'Neodymium', atomicNumber: 60, group: 'lanthanide', period: 6, category: 'lanthanide' },
        { symbol: 'Pm', name: '钷', englishName: 'Promethium', atomicNumber: 61, group: 'lanthanide', period: 6, category: 'lanthanide' },
        { symbol: 'Sm', name: '钐', englishName: 'Samarium', atomicNumber: 62, group: 'lanthanide', period: 6, category: 'lanthanide' },
        { symbol: 'Eu', name: '铕', englishName: 'Europium', atomicNumber: 63, group: 'lanthanide', period: 6, category: 'lanthanide' },
        { symbol: 'Gd', name: '钆', englishName: 'Gadolinium', atomicNumber: 64, group: 'lanthanide', period: 6, category: 'lanthanide' },
        { symbol: 'Tb', name: '铽', englishName: 'Terbium', atomicNumber: 65, group: 'lanthanide', period: 6, category: 'lanthanide' },
        { symbol: 'Dy', name: '镝', englishName: 'Dysprosium', atomicNumber: 66, group: 'lanthanide', period: 6, category: 'lanthanide' },
        { symbol: 'Ho', name: '钬', englishName: 'Holmium', atomicNumber: 67, group: 'lanthanide', period: 6, category: 'lanthanide' },
        { symbol: 'Er', name: '铒', englishName: 'Erbium', atomicNumber: 68, group: 'lanthanide', period: 6, category: 'lanthanide' },
        { symbol: 'Tm', name: '铥', englishName: 'Thulium', atomicNumber: 69, group: 'lanthanide', period: 6, category: 'lanthanide' },
        { symbol: 'Yb', name: '镱', englishName: 'Ytterbium', atomicNumber: 70, group: 'lanthanide', period: 6, category: 'lanthanide' },
        { symbol: 'Lu', name: '镥', englishName: 'Lutetium', atomicNumber: 71, group: 'lanthanide', period: 6, category: 'lanthanide' }
    ];

    // 锕系元素
    const actinides = [
        { symbol: 'Th', name: '钍', englishName: 'Thorium', atomicNumber: 90, group: 'actinide', period: 7, category: 'actinide' },
        { symbol: 'Pa', name: '镤', englishName: 'Protactinium', atomicNumber: 91, group: 'actinide', period: 7, category: 'actinide' },
        { symbol: 'U', name: '铀', englishName: 'Uranium', atomicNumber: 92, group: 'actinide', period: 7, category: 'actinide' },
        { symbol: 'Np', name: '镎', englishName: 'Neptunium', atomicNumber: 93, group: 'actinide', period: 7, category: 'actinide' },
        { symbol: 'Pu', name: '钚', englishName: 'Plutonium', atomicNumber: 94, group: 'actinide', period: 7, category: 'actinide' },
        { symbol: 'Am', name: '镅', englishName: 'Americium', atomicNumber: 95, group: 'actinide', period: 7, category: 'actinide' },
        { symbol: 'Cm', name: '锔', englishName: 'Curium', atomicNumber: 96, group: 'actinide', period: 7, category: 'actinide' },
        { symbol: 'Bk', name: '锫', englishName: 'Berkelium', atomicNumber: 97, group: 'actinide', period: 7, category: 'actinide' },
        { symbol: 'Cf', name: '锎', englishName: 'Californium', atomicNumber: 98, group: 'actinide', period: 7, category: 'actinide' },
        { symbol: 'Es', name: '锿', englishName: 'Einsteinium', atomicNumber: 99, group: 'actinide', period: 7, category: 'actinide' },
        { symbol: 'Fm', name: '镄', englishName: 'Fermium', atomicNumber: 100, group: 'actinide', period: 7, category: 'actinide' },
        { symbol: 'Md', name: '钔', englishName: 'Mendelevium', atomicNumber: 101, group: 'actinide', period: 7, category: 'actinide' },
        { symbol: 'No', name: '锘', englishName: 'Nobelium', atomicNumber: 102, group: 'actinide', period: 7, category: 'actinide' },
        { symbol: 'Lr', name: '铹', englishName: 'Lawrencium', atomicNumber: 103, group: 'actinide', period: 7, category: 'actinide' }
    ];

    // 添加所有元素的基础数据
    [...importantElements, ...lanthanides, ...actinides].forEach(element => {
        if (!elementsData[element.atomicNumber]) {
            elementsData[element.atomicNumber] = {
                ...element,
                atomicMass: 0, // 默认值，实际应用中需要填入真实值
                electronConfiguration: 'Unknown',
                electronegativity: null,
                atomicRadius: null,
                ionizationEnergy: null,
                meltingPoint: null,
                boilingPoint: null,
                density: null,
                state: 'unknown',
                oxidationStates: [],
                bondingType: 'unknown',
                crystalStructure: 'unknown',
                thermalConductivity: null,
                electricalResistivity: null,
                magneticOrdering: 'unknown',
                speedOfSound: null,
                modulus: { bulk: null, shear: null, young: null },
                hardness: { mohs: null, vickers: null, brinell: null },
                abundance: { earth: null, universe: null }
            };
        }
    });
}

// 生成完整的元素数据
generateFullElementsData();